#lang racket

; Load the internal libraries
(require htdp/error)
(require json)
(require racket/port)
(require racket/format)
(require net/url)
(require db)

(define database-name "retail_services.db")
(define database (sqlite3-connect #:database database-name))
(define hardware-limit 1000)
(define test-mode false)

; Provide the external structs
(provide
    (struct-out inventories)
    (struct-out time)
    (struct-out sales)
    (struct-out ratio)
    (struct-out data)
    (struct-out report)
    get-report
    main)

; Define the structs
(define-struct inventories
    (floor-covering-stores grocery-stores limited-service-eating-places shoe-stores health-and-personal-care-stores miscellaneous-store-retailers sporting-goods-stores family-clothing-stores drinking-places other-general-merchandise-stores home-furnishings-stores hardware-stores auto-and-other-motor-vehicles food-and-beverage-stores men's-clothing-stores sporting-goods,-hobby,-book,-and-music-stores used-merchandise-stores furniture,-home-furn,-electronics,-and-appliance-stores gasoline-stations other-clothing-stores office-supplies,-stationery,-and-gift-stores discount-department-stores building-supplies-dealers automotive-parts-and-tire-stores general-merchandise-stores motor-vehicle-and-parts-dealers all-other-merchandise-stores new-car-dealers household-appliance-stores electronics-and-appliance-stores non-leased-department-stores furniture-and-home-furnishings-stores all-department-stores pharmacies-and-drug-stores radio,-tv,-and-electronics-stores food-services-and-drinking-places appliances-and-other-electronics-stores beer,-wine,-and-liquor-stores fuel-dealers office-supplies-and-stationery-stores automobile-dealers retail-trade,-ex-auto gift,-novelty,-and-souvenir-stores retail-trade-and-food-services,-ex-auto retail-trade building-materials-and-garden-supplies-dealers supermarkets-and-other-grocery-(except-convenience)-stores book-stores furniture-stores gafo electronic-shopping-and-mail-order-houses clothing-stores used-car-dealers full-service-restaurants warehouse-clubs-and-superstores hobby,-toy,-and-game-stores nonstore-retailers all-other-home-furnishings-stores retail-trade-and-food-services paint-and-wallpaper-stores women's-clothing-stores computer-and-software-stores jewelry-stores non-discount-department-stores))

(define-struct time
    (month-name month index period year))

(define-struct sales
    (floor-covering-stores grocery-stores limited-service-eating-places shoe-stores health-and-personal-care-stores miscellaneous-store-retailers sporting-goods-stores family-clothing-stores drinking-places other-general-merchandise-stores home-furnishings-stores hardware-stores auto-and-other-motor-vehicles food-and-beverage-stores men's-clothing-stores sporting-goods,-hobby,-book,-and-music-stores used-merchandise-stores furniture,-home-furn,-electronics,-and-appliance-stores gasoline-stations other-clothing-stores office-supplies,-stationery,-and-gift-stores discount-department-stores building-supplies-dealers automotive-parts-and-tire-stores general-merchandise-stores motor-vehicle-and-parts-dealers all-other-merchandise-stores new-car-dealers household-appliance-stores electronics-and-appliance-stores non-leased-department-stores furniture-and-home-furnishings-stores all-department-stores pharmacies-and-drug-stores radio,-tv,-and-electronics-stores food-services-and-drinking-places appliances-and-other-electronics-stores beer,-wine,-and-liquor-stores fuel-dealers office-supplies-and-stationery-stores automobile-dealers retail-trade,-ex-auto gift,-novelty,-and-souvenir-stores retail-trade-and-food-services,-ex-auto retail-trade building-materials-and-garden-supplies-dealers supermarkets-and-other-grocery-(except-convenience)-stores book-stores furniture-stores gafo electronic-shopping-and-mail-order-houses clothing-stores used-car-dealers full-service-restaurants warehouse-clubs-and-superstores hobby,-toy,-and-game-stores nonstore-retailers all-other-home-furnishings-stores retail-trade-and-food-services paint-and-wallpaper-stores women's-clothing-stores computer-and-software-stores jewelry-stores non-discount-department-stores))

(define-struct ratio
    (floor-covering-stores grocery-stores limited-service-eating-places shoe-stores health-and-personal-care-stores miscellaneous-store-retailers sporting-goods-stores family-clothing-stores drinking-places other-general-merchandise-stores home-furnishings-stores hardware-stores auto-and-other-motor-vehicles food-and-beverage-stores men's-clothing-stores sporting-goods,-hobby,-book,-and-music-stores used-merchandise-stores furniture,-home-furn,-electronics,-and-appliance-stores gasoline-stations other-clothing-stores office-supplies,-stationery,-and-gift-stores discount-department-stores building-supplies-dealers automotive-parts-and-tire-stores general-merchandise-stores motor-vehicle-and-parts-dealers all-other-merchandise-stores new-car-dealers household-appliance-stores electronics-and-appliance-stores non-leased-department-stores furniture-and-home-furnishings-stores all-department-stores pharmacies-and-drug-stores radio,-tv,-and-electronics-stores food-services-and-drinking-places appliances-and-other-electronics-stores beer,-wine,-and-liquor-stores fuel-dealers office-supplies-and-stationery-stores automobile-dealers retail-trade,-ex-auto gift,-novelty,-and-souvenir-stores retail-trade-and-food-services,-ex-auto retail-trade building-materials-and-garden-supplies-dealers supermarkets-and-other-grocery-(except-convenience)-stores book-stores furniture-stores gafo electronic-shopping-and-mail-order-houses clothing-stores used-car-dealers full-service-restaurants warehouse-clubs-and-superstores hobby,-toy,-and-game-stores nonstore-retailers all-other-home-furnishings-stores retail-trade-and-food-services paint-and-wallpaper-stores women's-clothing-stores computer-and-software-stores jewelry-stores non-discount-department-stores))

(define-struct data
    (inventories ratio sales))

(define-struct report
    (data time))



; Define the JSON->Struct mappers
(define (json->inventories jdata)
    (make-inventories
        (hash-ref jdata (string->symbol "floor covering stores"))
            (hash-ref jdata (string->symbol "grocery stores"))
            (hash-ref jdata (string->symbol "limited service eating places"))
            (hash-ref jdata (string->symbol "shoe stores"))
            (hash-ref jdata (string->symbol "health and personal care stores"))
            (hash-ref jdata (string->symbol "miscellaneous store retailers"))
            (hash-ref jdata (string->symbol "sporting goods stores"))
            (hash-ref jdata (string->symbol "family clothing stores"))
            (hash-ref jdata (string->symbol "drinking places"))
            (hash-ref jdata (string->symbol "other general merchandise stores"))
            (hash-ref jdata (string->symbol "home furnishings stores"))
            (hash-ref jdata (string->symbol "hardware stores"))
            (hash-ref jdata (string->symbol "auto and other motor vehicles"))
            (hash-ref jdata (string->symbol "food and beverage stores"))
            (hash-ref jdata (string->symbol "men's clothing stores"))
            (hash-ref jdata (string->symbol "sporting goods, hobby, book, and music stores"))
            (hash-ref jdata (string->symbol "used merchandise stores"))
            (hash-ref jdata (string->symbol "furniture, home furn, electronics, and appliance stores"))
            (hash-ref jdata (string->symbol "gasoline stations"))
            (hash-ref jdata (string->symbol "other clothing stores"))
            (hash-ref jdata (string->symbol "office supplies, stationery, and gift stores"))
            (hash-ref jdata (string->symbol "discount department stores"))
            (hash-ref jdata (string->symbol "building supplies dealers"))
            (hash-ref jdata (string->symbol "automotive parts and tire stores"))
            (hash-ref jdata (string->symbol "general merchandise stores"))
            (hash-ref jdata (string->symbol "motor vehicle and parts dealers"))
            (hash-ref jdata (string->symbol "all other merchandise stores"))
            (hash-ref jdata (string->symbol "new car dealers"))
            (hash-ref jdata (string->symbol "household appliance stores"))
            (hash-ref jdata (string->symbol "electronics and appliance stores"))
            (hash-ref jdata (string->symbol "non-leased department stores"))
            (hash-ref jdata (string->symbol "furniture and home furnishings stores"))
            (hash-ref jdata (string->symbol "all department stores"))
            (hash-ref jdata (string->symbol "pharmacies and drug stores"))
            (hash-ref jdata (string->symbol "radio, TV, and electronics stores"))
            (hash-ref jdata (string->symbol "food services and drinking places"))
            (hash-ref jdata (string->symbol "appliances and other electronics stores"))
            (hash-ref jdata (string->symbol "beer, wine, and liquor stores"))
            (hash-ref jdata (string->symbol "fuel dealers"))
            (hash-ref jdata (string->symbol "office supplies and stationery stores"))
            (hash-ref jdata (string->symbol "automobile dealers"))
            (hash-ref jdata (string->symbol "retail trade, ex auto"))
            (hash-ref jdata (string->symbol "gift, novelty, and souvenir stores"))
            (hash-ref jdata (string->symbol "retail trade and food services, ex auto"))
            (hash-ref jdata (string->symbol "retail trade"))
            (hash-ref jdata (string->symbol "building materials and garden supplies dealers"))
            (hash-ref jdata (string->symbol "supermarkets and other grocery (except convenience) stores"))
            (hash-ref jdata (string->symbol "book stores"))
            (hash-ref jdata (string->symbol "furniture stores"))
            (hash-ref jdata (string->symbol "gafo"))
            (hash-ref jdata (string->symbol "electronic shopping and mail-order houses"))
            (hash-ref jdata (string->symbol "clothing stores"))
            (hash-ref jdata (string->symbol "used car dealers"))
            (hash-ref jdata (string->symbol "full service restaurants"))
            (hash-ref jdata (string->symbol "warehouse clubs and superstores"))
            (hash-ref jdata (string->symbol "hobby, toy, and game stores"))
            (hash-ref jdata (string->symbol "nonstore retailers"))
            (hash-ref jdata (string->symbol "all other home furnishings stores"))
            (hash-ref jdata (string->symbol "retail trade and food services"))
            (hash-ref jdata (string->symbol "paint and wallpaper stores"))
            (hash-ref jdata (string->symbol "women's clothing stores"))
            (hash-ref jdata (string->symbol "computer and software stores"))
            (hash-ref jdata (string->symbol "jewelry stores"))
            (hash-ref jdata (string->symbol "non-discount department stores"))
            ))

(define (json->time jdata)
    (make-time
        (hash-ref jdata (string->symbol "month name"))
            (hash-ref jdata (string->symbol "month"))
            (hash-ref jdata (string->symbol "index"))
            (hash-ref jdata (string->symbol "period"))
            (hash-ref jdata (string->symbol "year"))
            ))

(define (json->sales jdata)
    (make-sales
        (hash-ref jdata (string->symbol "floor covering stores"))
            (hash-ref jdata (string->symbol "grocery stores"))
            (hash-ref jdata (string->symbol "limited service eating places"))
            (hash-ref jdata (string->symbol "shoe stores"))
            (hash-ref jdata (string->symbol "health and personal care stores"))
            (hash-ref jdata (string->symbol "miscellaneous store retailers"))
            (hash-ref jdata (string->symbol "sporting goods stores"))
            (hash-ref jdata (string->symbol "family clothing stores"))
            (hash-ref jdata (string->symbol "drinking places"))
            (hash-ref jdata (string->symbol "other general merchandise stores"))
            (hash-ref jdata (string->symbol "home furnishings stores"))
            (hash-ref jdata (string->symbol "hardware stores"))
            (hash-ref jdata (string->symbol "auto and other motor vehicles"))
            (hash-ref jdata (string->symbol "food and beverage stores"))
            (hash-ref jdata (string->symbol "men's clothing stores"))
            (hash-ref jdata (string->symbol "sporting goods, hobby, book, and music stores"))
            (hash-ref jdata (string->symbol "used merchandise stores"))
            (hash-ref jdata (string->symbol "furniture, home furn, electronics, and appliance stores"))
            (hash-ref jdata (string->symbol "gasoline stations"))
            (hash-ref jdata (string->symbol "other clothing stores"))
            (hash-ref jdata (string->symbol "office supplies, stationery, and gift stores"))
            (hash-ref jdata (string->symbol "discount department stores"))
            (hash-ref jdata (string->symbol "building supplies dealers"))
            (hash-ref jdata (string->symbol "automotive parts and tire stores"))
            (hash-ref jdata (string->symbol "general merchandise stores"))
            (hash-ref jdata (string->symbol "motor vehicle and parts dealers"))
            (hash-ref jdata (string->symbol "all other merchandise stores"))
            (hash-ref jdata (string->symbol "new car dealers"))
            (hash-ref jdata (string->symbol "household appliance stores"))
            (hash-ref jdata (string->symbol "electronics and appliance stores"))
            (hash-ref jdata (string->symbol "non-leased department stores"))
            (hash-ref jdata (string->symbol "furniture and home furnishings stores"))
            (hash-ref jdata (string->symbol "all department stores"))
            (hash-ref jdata (string->symbol "pharmacies and drug stores"))
            (hash-ref jdata (string->symbol "radio, TV, and electronics stores"))
            (hash-ref jdata (string->symbol "food services and drinking places"))
            (hash-ref jdata (string->symbol "appliances and other electronics stores"))
            (hash-ref jdata (string->symbol "beer, wine, and liquor stores"))
            (hash-ref jdata (string->symbol "fuel dealers"))
            (hash-ref jdata (string->symbol "office supplies and stationery stores"))
            (hash-ref jdata (string->symbol "automobile dealers"))
            (hash-ref jdata (string->symbol "retail trade, ex auto"))
            (hash-ref jdata (string->symbol "gift, novelty, and souvenir stores"))
            (hash-ref jdata (string->symbol "retail trade and food services, ex auto"))
            (hash-ref jdata (string->symbol "retail trade"))
            (hash-ref jdata (string->symbol "building materials and garden supplies dealers"))
            (hash-ref jdata (string->symbol "supermarkets and other grocery (except convenience) stores"))
            (hash-ref jdata (string->symbol "book stores"))
            (hash-ref jdata (string->symbol "furniture stores"))
            (hash-ref jdata (string->symbol "gafo"))
            (hash-ref jdata (string->symbol "electronic shopping and mail-order houses"))
            (hash-ref jdata (string->symbol "clothing stores"))
            (hash-ref jdata (string->symbol "used car dealers"))
            (hash-ref jdata (string->symbol "full service restaurants"))
            (hash-ref jdata (string->symbol "warehouse clubs and superstores"))
            (hash-ref jdata (string->symbol "hobby, toy, and game stores"))
            (hash-ref jdata (string->symbol "nonstore retailers"))
            (hash-ref jdata (string->symbol "all other home furnishings stores"))
            (hash-ref jdata (string->symbol "retail trade and food services"))
            (hash-ref jdata (string->symbol "paint and wallpaper stores"))
            (hash-ref jdata (string->symbol "women's clothing stores"))
            (hash-ref jdata (string->symbol "computer and software stores"))
            (hash-ref jdata (string->symbol "jewelry stores"))
            (hash-ref jdata (string->symbol "non-discount department stores"))
            ))

(define (json->ratio jdata)
    (make-ratio
        (hash-ref jdata (string->symbol "floor covering stores"))
            (hash-ref jdata (string->symbol "grocery stores"))
            (hash-ref jdata (string->symbol "limited service eating places"))
            (hash-ref jdata (string->symbol "shoe stores"))
            (hash-ref jdata (string->symbol "health and personal care stores"))
            (hash-ref jdata (string->symbol "miscellaneous store retailers"))
            (hash-ref jdata (string->symbol "sporting goods stores"))
            (hash-ref jdata (string->symbol "family clothing stores"))
            (hash-ref jdata (string->symbol "drinking places"))
            (hash-ref jdata (string->symbol "other general merchandise stores"))
            (hash-ref jdata (string->symbol "home furnishings stores"))
            (hash-ref jdata (string->symbol "hardware stores"))
            (hash-ref jdata (string->symbol "auto and other motor vehicles"))
            (hash-ref jdata (string->symbol "food and beverage stores"))
            (hash-ref jdata (string->symbol "men's clothing stores"))
            (hash-ref jdata (string->symbol "sporting goods, hobby, book, and music stores"))
            (hash-ref jdata (string->symbol "used merchandise stores"))
            (hash-ref jdata (string->symbol "furniture, home furn, electronics, and appliance stores"))
            (hash-ref jdata (string->symbol "gasoline stations"))
            (hash-ref jdata (string->symbol "other clothing stores"))
            (hash-ref jdata (string->symbol "office supplies, stationery, and gift stores"))
            (hash-ref jdata (string->symbol "discount department stores"))
            (hash-ref jdata (string->symbol "building supplies dealers"))
            (hash-ref jdata (string->symbol "automotive parts and tire stores"))
            (hash-ref jdata (string->symbol "general merchandise stores"))
            (hash-ref jdata (string->symbol "motor vehicle and parts dealers"))
            (hash-ref jdata (string->symbol "all other merchandise stores"))
            (hash-ref jdata (string->symbol "new car dealers"))
            (hash-ref jdata (string->symbol "household appliance stores"))
            (hash-ref jdata (string->symbol "electronics and appliance stores"))
            (hash-ref jdata (string->symbol "non-leased department stores"))
            (hash-ref jdata (string->symbol "furniture and home furnishings stores"))
            (hash-ref jdata (string->symbol "all department stores"))
            (hash-ref jdata (string->symbol "pharmacies and drug stores"))
            (hash-ref jdata (string->symbol "radio, TV, and electronics stores"))
            (hash-ref jdata (string->symbol "food services and drinking places"))
            (hash-ref jdata (string->symbol "appliances and other electronics stores"))
            (hash-ref jdata (string->symbol "beer, wine, and liquor stores"))
            (hash-ref jdata (string->symbol "fuel dealers"))
            (hash-ref jdata (string->symbol "office supplies and stationery stores"))
            (hash-ref jdata (string->symbol "automobile dealers"))
            (hash-ref jdata (string->symbol "retail trade, ex auto"))
            (hash-ref jdata (string->symbol "gift, novelty, and souvenir stores"))
            (hash-ref jdata (string->symbol "retail trade and food services, ex auto"))
            (hash-ref jdata (string->symbol "retail trade"))
            (hash-ref jdata (string->symbol "building materials and garden supplies dealers"))
            (hash-ref jdata (string->symbol "supermarkets and other grocery (except convenience) stores"))
            (hash-ref jdata (string->symbol "book stores"))
            (hash-ref jdata (string->symbol "furniture stores"))
            (hash-ref jdata (string->symbol "gafo"))
            (hash-ref jdata (string->symbol "electronic shopping and mail-order houses"))
            (hash-ref jdata (string->symbol "clothing stores"))
            (hash-ref jdata (string->symbol "used car dealers"))
            (hash-ref jdata (string->symbol "full service restaurants"))
            (hash-ref jdata (string->symbol "warehouse clubs and superstores"))
            (hash-ref jdata (string->symbol "hobby, toy, and game stores"))
            (hash-ref jdata (string->symbol "nonstore retailers"))
            (hash-ref jdata (string->symbol "all other home furnishings stores"))
            (hash-ref jdata (string->symbol "retail trade and food services"))
            (hash-ref jdata (string->symbol "paint and wallpaper stores"))
            (hash-ref jdata (string->symbol "women's clothing stores"))
            (hash-ref jdata (string->symbol "computer and software stores"))
            (hash-ref jdata (string->symbol "jewelry stores"))
            (hash-ref jdata (string->symbol "non-discount department stores"))
            ))

(define (json->data jdata)
    (make-data
        (json->inventories (hash-ref jdata (string->symbol "inventories")))
                (json->ratio (hash-ref jdata (string->symbol "ratio")))
                (json->sales (hash-ref jdata (string->symbol "sales")))
                ))

(define (json->report jdata)
    (make-report
        (json->data (hash-ref jdata (string->symbol "data")))
                (json->time (hash-ref jdata (string->symbol "time")))
                ))



; Define the services, and their helpers

(define (get-report [test #t]) 

    (if (or test-mode test)
        (let* [(result (query-list database 
                                  (format "SELECT data FROM retail_services LIMIT ~a" hardware-limit)
                                ))
               (result (map string->jsexpr result))]
           (map json->report result)
           )(let* [(result (query-list database 
                                   "SELECT data FROM retail_services"
                                ))
               (result (map string->jsexpr result))
               ]
           (map json->report result)
           ))
)


(define (main)
    (displayln "Running tests")
    
    (displayln "Production get-report")
    (displayln (length (time (get-report false))))
    (displayln "Test get-report")
    (displayln (length (time (get-report true))))
    
    

    )